name: colored_logger
description: "A Flutter package for colored terminal logs (VS Code, Android Studio, IntelliJ) with Ansi escape codes."
version: 1.1.0
homepage: https://www.venhdev.me
repository: https://github.com/venhdev/colored_logger

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
