name: colored_logger
description: "A Dart package for colored terminal logs (VS Code, Android Studio, IntelliJ) with Ansi escape codes."
version: 2.0.6
homepage: https://github.com/venhdev/colored_logger
repository: https://github.com/venhdev/colored_logger

environment:
  sdk: ">=2.17.0 <4.0.0"

topics:
  - logging
  - cli
  - pretty
  - ansi
  - colored

dependencies:

dev_dependencies:
  lints: any
  test: ^1.24.0